### Lisää uusi blogi ###
POST http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpIiwiaWQiOiI2NjQ2MmUwYmM5NGJmZmQ4MDViMzNmNjAiLCJpYXQiOjE3MTU4NzUzNTQsImV4cCI6MTcxNTg3ODk1NH0.lFr8KdbeRGcj8ahyk1lfDPcKxIzpeqYtRMkCUos-jeo
Content-Type: application/json

{
  "title": "blaaoeeeI",
  "author": "Testi oee",
  "url": "https://jauuu.com",
  "likes": 2000
}

###

### Näytä tietokannan sisältö ###
GET http://localhost:3003/api/blogs

###

### Poista blogi ###
DELETE http://localhost:3003/api/blogs/663cf89994c2456c9345f153



###
