@baseUrl = http://localhost:3003

### Create User
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "username": "testi",
  "password": "testi",
  "name": "testi käyttäjä"
}

### Get All Users
GET {{baseUrl}}/api/users